### ISSUE TITLE
Error when registering command

### ISSUE THREAD

**Issue by LemADEC** [Zerthick/PlayerShopsRPG#23]
As of PlayerShopsRPG-v1.1.0 & spongeforge-1.10.2-2281-5.2.0-BETA-2353, the following error is reported at boot
```
[16:43:50] [Server thread/ERROR] [Sponge]: Could not pass FMLServerStartedEvent to Plugin{id=playershopsrpg, name=PlayerShopsRPG, version=1.1.0, description=A region-based player shop plugin., authors=[Zerthick], source=/home/skyfactory30/./plugins/PlayerShopsRPG-v1.1.0.jar}
java.lang.NullPointerException
>       at io.github.zerthick.playershopsrpg.cmd.CommandRegister.registerCommands(CommandRegister.java:186) ~[CommandRegister.class:?]
>       at io.github.zerthick.playershopsrpg.PlayerShopsRPG.onServerStart(PlayerShopsRPG.java:136) ~[PlayerShopsRPG.class:?]
>       at org.spongepowered.common.event.listener.GameStartedServerEventListener_PlayerShopsRPG_onServerStart24.handle(Unknown Source) ~[?:?]
>       at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2353]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2353]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342) [SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2353]
>       at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234) [SpongeMod.class:1.10.2-2281-5.2.0-BETA-2353]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
>       at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
>       at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243) [LoadController.class:?]
>       at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221) [LoadController.class:?]
>       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
>       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
>       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
>       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
>       at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [minecraft_server.1.10.2.jar:?]
>       at com.google.common.eventbus.EventBus.post(EventBus.java:275) [minecraft_server.1.10.2.jar:?]
>       at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552) [LoadController.class:?]
>       at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145) [LoadController.class:?]
>       at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:868) [Loader.class:?]
>       at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:297) [FMLCommonHandler.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

**Comment by Zerthick** [comment]
Does this still occur on [v2.2.0](https://github.com/Zerthick/PlayerShopsRPG/releases/tag/v2.0.0)?

**Comment by LemADEC** [comment]
I understand it's a full rewrite. Is there some ascendant compatibility of configuration and shops?
What happens if I rollback because of an issue?

**Comment by Zerthick** [comment]
Your old `shops.conf` file will be updated and a backup will be created called `shops_old.conf`. I do recommend that you do your own backup before updating however.  If for some reason you need to roll back delete the database file called `data.mv.db` and rename your shops config back to `shops.conf`, then you can utilize an older version and all of your old shops should load up just fine.

**Comment by LemADEC** [comment]
I don't see the issue anymore with spongeforge-1.10.2-2281-5.2.0-BETA-2353.jar and plugins/PlayerShopsRPG-v1.1.0.jar nor plugins/PlayerShopsRPG-v2.0.0.jar

**Comment by Zerthick** [comment]
Good, I'm glad it was resolved!
