### ISSUE TITLE
Unable to add Item to a Shop

### ISSUE THREAD

**Issue by Mareron** [Zerthick/PlayerShopsRPG#30]
Heyho,
I have recently Installed the latest Update to this amazing Plugin but ever since I am unable to add Items to any shop.
I have removed the message.config and old shop files as mentioned in the update post but it still keeps giving me the following message

[03:40:39] [Server thread/ERROR] [Sponge/]: Error occurred while executing command 'shop item add' for source EntityPlayerMP['LordMareron'/228, l='world', x=-1038.00, y=68.00, z=3070.78]: org.spongepowered.api.item.inventory.entity.PlayerInventory.queryAny([Lorg/spongepowered/api/item/inventory/ItemStack;)Lorg/spongepowered/api/item/inventory/Inventory;
java.lang.NoSuchMethodError: org.spongepowered.api.item.inventory.entity.PlayerInventory.queryAny([Lorg/spongepowered/api/item/inventory/ItemStack;)Lorg/spongepowered/api/item/inventory/Inventory;
	at io.github.zerthick.playershopsrpg.utils.inventory.InventoryUtils.getItemCount(InventoryUtils.java:36) ~[InventoryUtils.class:?]
	at io.github.zerthick.playershopsrpg.utils.inventory.InventoryUtils.removeItem(InventoryUtils.java:100) ~[InventoryUtils.class:?]
	at io.github.zerthick.playershopsrpg.shop.Shop.addItem(Shop.java:286) ~[Shop.class:?]
	at io.github.zerthick.playershopsrpg.cmd.cmdexecutors.shop.item.ShopAddItemExecutor.lambda$execute$11(ShopAddItemExecutor.java:51) ~[ShopAddItemExecutor.class:?]
	at io.github.zerthick.playershopsrpg.cmd.cmdexecutors.AbstractShopTransactionCmdExecutor.executeTransaction(AbstractShopTransactionCmdExecutor.java:58) ~[AbstractShopTransactionCmdExecutor.class:?]
	at io.github.zerthick.playershopsrpg.cmd.cmdexecutors.shop.item.ShopAddItemExecutor.execute(ShopAddItemExecutor.java:44) ~[ShopAddItemExecutor.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.10.2-2281-5.2.0-BETA-2464]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:182) ~[ChildCommandElementExecutor.class:1.10.2-2281-5.2.0-BETA-2464]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:359) ~[CommandSpec.class:1.10.2-2281-5.2.0-BETA-2464]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:336) ~[SimpleDispatcher.class:1.10.2-2281-5.2.0-BETA-2464]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:291) ~[SpongeCommandManager.class:1.10.2-2281-5.2.0-BETA-2464]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) ~[bd.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) ~[me.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
	at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2464]
	at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:162) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2464]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2464]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjj000(SourceFile:539) [fl$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2464]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zhp000(MinecraftServer.java:3932) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by Mareron** [comment]
Nevermind, I used 2.0.3 instead of 2.0.4, it works on the latest version
